openapi: 3.0.0
info:
  title: Metrics Lambda Function API
  version: 1.0.0
paths:
  /metric:
    post:
      summary: Add a record to the Kinesis stream.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the record.
                value:
                  type: number
                  description: The value of the record.
                timestamp:
                  type: string
                  format: date-time
                  description: The timestamp of the record.
              required:
                - name
                - value
                - timestamp
      responses:
        '200':
          description: Record added successfully.
        '500':
          description: Error handling the request.
