name: Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install API dependencies
        working-directory: api
        run: yarn
      
      - name: Lint API
        working-directory: api
        run: yarn lint

      - name: Test API
        working-directory: api
        run: yarn test
      
      - name: Build API
        working-directory: api
        run: yarn build
  validate_client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    needs: validate_api
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Change directory to root
        run: |
          pwd
      - name: Change directory to root2
        run: |
          ls -al

      - name: Install Client dependencies
        working-directory: client
        run: yarn
      
      - name: Lint Client
        working-directory: client
        run: yarn lint

      - name: Test Client
        working-directory: client
        run: yarn test
      
      - name: Build Client
        working-directory: client
        run: yarn build
     
